os: linux
language: java
jdk: openjdk8

services:
  - docker

install:
  - openssl aes-256-cbc -K $encrypted_99693b848002_key -iv $encrypted_99693b848002_iv -in signing-key.gpg.enc -out signing-key.gpg -d
  - cp .travis.settings.xml ${HOME}/.m2/settings.xml

before_script:
  - if [ "${TRAVIS_BRANCH}" = "master" ]; then mvn versions:set -DremoveSnapshot=true; else echo "Leaving version as SNAPSHOT"; fi

script:
  - mvn verify

after_success:
  - mvn coveralls:report

deploy:
  - provider: script
    cleanup: false
    script: mvn deploy -Dmaven.test.skip=true
    on:
      all_branches: true
      condition: "${TRAVIS_BRANCH} =~ ^((release\\/.*)|(master))$"
