os: linux
language: java
jdk: openjdk8
services:
  - docker

install:
  - cp .travis.settings.xml ${HOME}/.m2/settings.xml

before_script:
  - if [ "${TRAVIS_BRANCH}" = "master" ]; then mvn version:set -DremoveSnapshot=true; else echo "Leaving version as SNAPSHOT"; fi

script:
  - mvn verify

deploy:
  - provider: script
    skip_cleanup: true
    script: "mvn deploy -Dmaven.test.skip=true"
    on:
      all_branches: true
      condition: ${TRAVIS_BRANCH} =~ ^((release\/.*)|(master))$